name: delectable
description: 'A plugin that enables integrating Delectable features into your app.'
version: 0.1.0
homepage: https://delectable.dev
repository: https://github.com/delectable-apps/delectable

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.delectable.delectable
        pluginClass: DelectablePlugin
      ios:
        pluginClass: DelectablePlugin
